CFLAGS = -std=c99 -Wall -Wextra -Os -g3 \
    -Wno-missing-field-initializers -D_POSIX_C_SOURCE=200809L -D_GNU_SOURCE
LDLIBS = -lm

memdig : memdig.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LDLIBS)

clean :
	$(RM) memdig
