CFLAGS = -std=c99 -Wall -Wextra -Os -g3 \
    -Wno-missing-field-initializers -D_POSIX_C_SOURCE=200809L
LDLIBS = -lm

memdig : memdig.c scan.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LDLIBS)

clean :
	$(RM) memdig
